### ISSUE TITLE
give an option in the script whether to encrypt or not.

### ISSUE THREAD

**Issue by ghost** [Zaechus/artix-installer#11]
this script is very good the best i've seen with my research but  i just need a system without encryption it will be very helpful if it had a choice whether to encrypt or not

**Comment by Zaechus** [comment]
Definitely a good idea, I'll give it a go and work on testing the changes in a bit

**Comment by ghost** [comment]
thank you very much i will peek from time to time on your repo to see if it got implemented.

**Comment by Zaechus** [comment]
I've implemented this as an option and tested an unencrypted ext4 install. I have not tested unencrypted btrfs. Let me know how your installation goes and I'll close this issue.

EDIT: All variations of btrfs/ext4, encrtyped/unencrypted have been tested.

**Comment by ghost** [comment]
i will definitely test it and i'll report back to you give me a couple of hours, and i would like to see btrfs get the option of a non encrtyped option as well its a pertty good filesystem thank you for your work.

**Comment by ghost** [comment]
i have tested your implementation and its working pretty well thanks for the added feature, i didn't test btrfs but i will soon 
are you considering adding hibernation to btrfs as a choice on your scripts ?

**Comment by Zaechus** [comment]
Hibernation is something I've never needed/tried to install on any filesystem, and I don't see myself adding support for it soon. At the moment the script gives you control over the size of the swap partition/volume, so using a larger size than the default 4GiB should allow for a trivial post-install hibernate configuration.

**Comment by ghost** [comment]
i see your point sorry for the late replay i had a lot of family stuff anyway thank you for your script and for your contribution to the gnu/linux community.
