### ISSUE TITLE
support other inits

### ISSUE THREAD

**Issue by Zaechus** [Zaechus/artix-installer#14]
I'm lazy and don't use anything but OpenRC, but I'll try to implement this eventually if anyone needs

**Comment by 1fate4all** [comment]
Could you add support for Dinit? Would be an a great addition to an already awesome script

**Comment by Zaechus** [comment]
At this point, I got a dinit install on LUKS encrypted Btrfs to work in a VM. `connman` had to be enabled again, but I'll look into that.

Go ahead and test it in the Artix live ISO with:
```
sudo pacman -Sy git glibc
git clone https://github.com/Zaechus/artix-installer
cd artix-installer
git checkout dinit
./install.sh
```

**Comment by Zaechus** [comment]
update: connman works immediately on first boot now
