### ISSUE TITLE
Desktop Environment (DE) choosing option

### ISSUE THREAD

**Issue by zcheese1** [Zaechus/artix-installer#18]
Please add a desktop environment selection option to facilitate the installation process on Artix Linux.!

**Comment by Zaechus** [comment]
Thank you for your suggestion, but this feature would not be a good fit. The installer aims to set up only the base system, and having multiple DE/WM options would unnecessarily complicate testing. DEs are better suited for post-installation with personal dotfiles scripts.

**Comment by zcheese1** [comment]
Understandable.
